FROM xrsec/php:init
LABEL maintainer="xrsec"
LABEL mail="troy@zygd.site"

RUN mkdir -p /www /www/server /www/bak /www/server/php56

RUN wget -O /www/bak/php56.tar.gz https://www.php.net/distributions/php-5.6.40.tar.gz --no-cookie --no-check-certificate \
    && wget -O /www/bak/xdebug-2.5.5.tar https://pecl.php.net/get/xdebug-2.5.5.tgz --no-cookie --no-check-certificate \
    && tar -xzvf /www/bak/php56.tar.gz -C /www/bak

RUN cd /www/bak/php-5.6.40 \
    && ./configure --prefix=/www/server/php56 --with-curl \
    --with-gettext --with-iconv-dir --with-kerberos --with-libdir=lib64 \
    --with-mysqli --with-pdo-mysql --with-pdo-sqlite --with-pear \
    --with-xmlrpc --with-xsl --with-zlib --with-bz2 --with-mhash \
    --enable-fpm --enable-bcmath --enable-inline-optimization \
    --enable-mbregex --enable-mbstring --enable-opcache --enable-pcntl --enable-shmop --enable-soap \
    --enable-sockets --enable-sysvsem --enable-sysvshm --enable-xml

RUN cd /www/bak/php-5.6.40 \
    && make && make install \
    && /www/bak/php-5.6.40/build/shtool install -c ext/phar/phar.phar /www/server/php56/bin \
    && ln -sf phar.phar /www/server/php56/bin/phar \
    && /www/server/php56/bin/pecl install /www/bak/xdebug-2.5.5.tar

RUN cp /www/bak/php-5.6.40/php.ini-development /www/server/php56/lib/php.ini \
    && echo "zend_extension=/www/server/php56/lib/php/extensions/no-debug-non-zts-20131226/xdebug.so" >> /www/server/php56/lib/php.ini \
    && echo "xdebug.remote_enable = on" >> /www/server/php56/lib/php.ini \
    && echo "xdebug.remote_host = docker.for.mac.localhost" >>/www/server/php56/lib/php.ini \
    && echo "xdebug.remote_port = 9003" >> /www/server/php56/lib/php.ini \
    && echo 'xdebug.idekey="PHPSTORM"' >> /www/server/php56/lib/php.ini \
    && echo "xdebug.remote_autostart = 1" >> /www/server/php56/lib/php.ini \
    && echo "xdebug.remote_connect_back = 1" >> /www/server/php56/lib/php.ini \
    && echo 'xdebug.remote_handler = "dbgp"' >> /www/server/php56/lib/php.ini \
    && cp /www/server/php56/etc/php-fpm.conf.default /www/server/php56/etc/php-fpm.conf \
    && ln -sf /www/server/php56/sbin/php-fpm /usr/bin/php56-fpm \
    && ln -sf /www/server/php56/bin/php /usr/bin/php56 \
    && ln -sf /www/server/php56/bin/pecl /usr/bin/php56-pecl \
    && ln -sf /www/server/php56/bin/pear /usr/bin/php56-pear

ENTRYPOINT ["/bin/bash"]

EXPOSE 9003

# ENV TZ='Asia/Shanghai'
# ENV LANG 'zh_CN.UTF-8'
# PHP_Run_Home : /www/server/php56/

STOPSIGNAL SIGQUIT

CMD ["/bin/bash"]