name: Docker PHP Build
  
on:
  push

jobs:
  Build_For_PHP_INIT:
    name: Docker Build PHP_INIT
    runs-on: ubuntu-latest
    steps:
      - 
        name: Private Actions Checkout
        uses: actions/checkout@v2.3.4
      - 
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - 
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - 
        name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          file: Dockerfiles/Dockerfile.init
          push: true
          tags: |
            xrsec/php:init
          cache-from: type=registry,ref=xrsec/php:init
          cache-to: type=registry,ref=xrsec/php:init,mode=max

  Build_For_PHP56:
    needs: Build_For_PHP_INIT
    name: Docker Build PHP56
    runs-on: ubuntu-latest
    steps:
      - 
        name: Private Actions Checkout
        uses: actions/checkout@v2.3.4
      - 
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - 
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - 
        name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          file: Dockerfiles/Dockerfile.56
          push: true
          tags: |
            xrsec/php:5.6
          cache-from: type=registry,ref=xrsec/php:5.6
          cache-to: type=registry,ref=xrsec/php:5.6,mode=max

  Build_For_PHP74:
    needs: Build_For_PHP_INIT
    name: Docker Build PHP74
    runs-on: ubuntu-latest
    steps:
      - 
        name: Private Actions Checkout
        uses: actions/checkout@v2.3.4
      - 
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - 
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - 
        name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          file: Dockerfiles/Dockerfile.74
          push: true
          tags: |
            xrsec/php:7.4
          cache-from: type=registry,ref=xrsec/php:7.4
          cache-to: type=registry,ref=xrsec/php:7.4,mode=max

  Build_For_PHP56_74:
    needs: [Build_For_PHP56, Build_For_PHP74]
    name: Docker Build PHP56_74
    runs-on: ubuntu-latest
    steps:
      - 
        name: Private Actions Checkout
        uses: actions/checkout@v2.3.4
      - 
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - 
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - 
        name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          file: Dockerfiles/Dockerfile.56_74
          push: true
          tags: |
            xrsec/php:latest
          cache-from: type=registry,ref=xrsec/php:latest
          cache-to: type=registry,ref=xrsec/php:latest,mode=max

  Repository_Dispatch:
    needs: Build_For_PHP56_74
    runs-on: ubuntu-latest
    steps:
      - 
        name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          repository: XRSec/Code-Server-Update
          event-type: PhpUpdate
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
